apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-{{ .Values.pvDbName }}
  labels:
    app: {{ .Values.labelAppDb }}
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.pvDbStorage }}
  accessModes:
    - {{ .Values.pvDbAccessModes }}
  nfs:
    server: {{ .Values.ipServerNfs }}
    path: {{ .Values.pathDbNfs | quote }} 



