apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Values.secretSqlRootName }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  password: {{ .Values.secretSqlRootPassword }}
  
  
  