apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-nginx-ingress-clusterrole-nisa-binding
  labels:
    app.kubernetes.io/name: {{ .Values.labels.name }}
    app.kubernetes.io/part-of: {{ .Values.labels.partOF }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-nginx-ingress-clusterrole
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-nginx-ingress-serviceaccount
    namespace: {{ .Values.namespace }}
