kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-udp-services
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.labels.name }}
    app.kubernetes.io/part-of: {{ .Values.labels.partOF }}
