apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-nginx-ingress-role-nisa-binding
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.labels.name }}
    app.kubernetes.io/part-of: {{ .Values.labels.partOF }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-nginx-ingress-role
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-nginx-ingress-serviceaccount
    namespace: {{ .Values.namespace }}