apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-nginx-ingress-serviceaccount
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.labels.name }}
    app.kubernetes.io/part-of: {{ .Values.labels.partOF }}